### ISSUE TITLE
Fix Lint Warnings

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPressKit-iOS#55]
This is the result of running `pod spec lint WordPressKit.podspec`:

>  -> WordPressKit (1.5.0)
>     - WARN  | url: There was a problem validating the URL http://apps.wordpress.com.
>     - NOTE  | xcodebuild:  note: Using new build system
>     - NOTE  | [iOS] xcodebuild:  note: Planning build
>     - NOTE  | [iOS] xcodebuild:  note: Constructing build description
>     - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
>     - WARN  | xcodebuild:  wpxmlrpc/WPXMLRPC/WPXMLRPCEncoder.h:50:9: warning: parameter 'parameters' not found in the function declaration [-Wdocumentation]
>     - NOTE  | xcodebuild:  wpxmlrpc/WPXMLRPC/WPXMLRPCEncoder.h:50:9: note: did you mean 'params'?
>     - WARN  | xcodebuild:  wpxmlrpc/WPXMLRPC/WPXMLRPCEncoder.h:92:3: warning: '@param' command used in a comment that is not attached to a function declaration [-Wdocumentation]

We should clean this up to build cleanly.

**Comment by jklausa** [comment]
Feel free to ping me if you need help with this!

**Comment by stevebaranski** [comment]
@jkmassel I believe the warnings have been [addressed](https://github.com/wordpress-mobile/wpxmlrpc/pull/42) already, but we haven't created a new version of `wpxmlrpc` and updated the dependency on it.
