### ISSUE TITLE
Blaze: Manage Campaigns - Implement the endpoint to fetch campaigns with sort/filter and pagination logic

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPressKit-iOS#604]
## Description 
Fetch the campaigns using the new endpoint which supports sort/filter and pagination logic 

## Links 
Design ref - 1Osrn9gb2xLaKG6lIft3WC-fi-1461_9777

```[tasklist]
### Todo
- [ ] Implement the API endpoint
- [ ] Implement the Unit test
```

**Comment by momo-ozawa** [comment]
Closing this issue:
- Pagination was already addressed in https://github.com/wordpress-mobile/WordPressKit-iOS/pull/605
- Descoped sort/filter
